name: build plugin


on:
  push:
    branches:
      - master

jobs:
  build_plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: eric2788/maven-jar-publish@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: 'for DragonNiteMC'